### GET

GET http://localhost:3000


### GET

GET http://localhost:3000/hello


### GET | TICKET

GET http://localhost:3000/hello/ticket/22


### GET | HELLO | STATUS

GET http://localhost:3000/hello/active/false


### GET | HELLO | QUERY

GET http://localhost:3000/hello/greet?name=Juan&age=33
Authorization: true


### GET | USER

GET http://localhost:3000/api/users


### GET | ID | USER

GET http://localhost:3000/api/users/3


### POST | CREATE | USER

POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: tech123

{
  "age": 39,
  "email": "test@test.com",
  "name": "Juan Luna",
  "password": "123456",
  "test": 123
}


### GET

GET http://localhost:3000/api/tasks


### GET | ID

GET http://localhost:3000/api/tasks/2


### GET | QUERY

GET http://localhost:3000/api/tasks?limit=5


### POST | CREATE | TASK

POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "age": 25,
  "name": "Juan Perez",
  "title": "Programador"
}


### PUT

PUT http://localhost:3000/api/tasks


### PATCH

PATCH http://localhost:3000/api/tasks


### DELETE

DELETE http://localhost:3000/api/tasks


### GET | AUTH

GET http://localhost:3000/auth


### GET | AUTH | NOT FOUND

GET http://localhost:3000/auth/notfount


### GET | AUTH | ERROR PAGE

GET http://localhost:3000/auth/error
