### GET

GET http://localhost:3000 HTTP/1.1


### GET

GET http://localhost:3000/hello HTTP/1.1


### GET | TICKET

GET http://localhost:3000/hello/ticket/22 HTTP/1.1


### GET | HELLO | STATUS

GET http://localhost:3000/hello/active/false HTTP/1.1


### GET | HELLO | QUERY

GET http://localhost:3000/hello/greet?name=Juan&age=33 HTTP/1.1
Authorization: true


### GET | USER

GET http://localhost:3000/api/users HTTP/1.1


### GET | ID | USER

GET http://localhost:3000/api/users/3 HTTP/1.1


### POST | CREATE | USER

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "age": 39,
  "email": "test@test.com",
  "name": "Juan Luna",
  "password": "123456",
  "test": 123
}


### GET

GET http://localhost:3000/api/tasks HTTP/1.1


### GET | ID

GET http://localhost:3000/api/tasks/2 HTTP/1.1


### GET | QUERY

GET http://localhost:3000/api/tasks?limit=5 HTTP/1.1


### POST | CREATE | TASK

POST http://localhost:3000/api/tasks HTTP/1.1
Content-Type: application/json

{
  "age": 25,
  "name": "Juan Perez",
  "title": "Programador"
}


### PUT

PUT http://localhost:3000/api/tasks HTTP/1.1


### PATCH

PATCH http://localhost:3000/api/tasks HTTP/1.1


### DELETE

DELETE http://localhost:3000/api/tasks HTTP/1.1


### GET | AUTH

GET http://localhost:3000/auth HTTP/1.1


### GET | AUTH | NOT FOUND

GET http://localhost:3000/auth/notfount HTTP/1.1 HTTP/1.1


### GET | AUTH | ERROR PAGE

GET http://localhost:3000/auth/error HTTP/1.1
